version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3thumbnailapp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10y2h1j8soecg"
s3_prefix = "s3thumbnailapp"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
